/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Group.Activity;

import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void testGetUserInput() {
        // test with valid input
        String input = "5\n";
        InputStream in = new ByteArrayInputStream(input.getBytes());
        System.setIn(in);
        int result = App.getUserInput();
        assertEquals(5, result);

        // test with negative input
        input = "-5\n5\n";
        in = new ByteArrayInputStream(input.getBytes());
        System.setIn(in);
        result = App.getUserInput();
        assertEquals(5, result);
    }

    @Test
    public void testEvenChecker() {
        // test with empty list
        List<Integer> emptyList = Collections.emptyList();
        List<Integer> result = App.even_Checker(emptyList);
        assertTrue(result.isEmpty());

        // test with odd numbers only
        List<Integer> oddList = Arrays.asList(1, 3, 5, 7, 9);
        result = App.even_Checker(oddList);
        assertTrue(result.isEmpty());

        // test with even and odd numbers
        List<Integer> mixedList = Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9);
        result = App.even_Checker(mixedList);
        List<Integer> expected = Arrays.asList(2, 4, 6, 8);
        assertEquals(expected, result);

        // test with even numbers only
        List<Integer> evenList = Arrays.asList(2, 4, 6, 8);
        result = App.even_Checker(evenList);
        assertEquals(evenList, result);
    }
}
